// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoTeca.AcessoDados.Contexto;

namespace VideoTeca.AcessoDados.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210513141738_Base-Inicial")]
    partial class BaseInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VideoTeca.Modelos.Modelos.Catalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnoLancamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ano_lancamento");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cod_catalogo");

                    b.Property<string>("DesTitulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("des_titulo");

                    b.Property<DateTime?>("DtcAtualizacao")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("dtc_atualizacao");

                    b.Property<int>("IdGenero")
                        .HasColumnType("int")
                        .HasColumnName("id_genero");

                    b.Property<string>("NomAutor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nom_autor");

                    b.HasKey("Id");

                    b.ToTable("catalogo");
                });

            modelBuilder.Entity("VideoTeca.Modelos.Modelos.CatalogoTipoMidia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DtcAtualizacao")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("dtc_atualizacao");

                    b.Property<int>("IdCatalogo")
                        .HasColumnType("int")
                        .HasColumnName("id_catalogo");

                    b.Property<int>("IdTipoMidia")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_midia");

                    b.Property<int>("QtdDisponivel")
                        .HasColumnType("int")
                        .HasColumnName("qtd_disponivel");

                    b.Property<int>("QtdTitulo")
                        .HasColumnType("int")
                        .HasColumnName("qtd_titulo");

                    b.HasKey("Id");

                    b.HasIndex("IdCatalogo");

                    b.HasIndex("IdTipoMidia");

                    b.ToTable("catalogo_tipo_midia");
                });

            modelBuilder.Entity("VideoTeca.Modelos.Modelos.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DesBairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("des_bairro");

                    b.Property<string>("DesComplemento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("des_complemento");

                    b.Property<string>("DesLogradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("des_logradouro");

                    b.Property<string>("DesMunicipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("des_municipio");

                    b.Property<DateTime?>("DtcAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtc_atualizacao");

                    b.Property<DateTime?>("DtcNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtc_nascimento");

                    b.Property<string>("NomCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nom_cliente");

                    b.Property<string>("NumCep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("num_cep");

                    b.Property<string>("NumDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("num_documento");

                    b.Property<string>("NumEndereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("num_endereco");

                    b.Property<string>("NumTelefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("num_telefone");

                    b.Property<byte>("TipoPessoa")
                        .HasColumnType("tinyint")
                        .HasColumnName("cod_tipo_pessoa");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("VideoTeca.Modelos.Modelos.ClienteCatalogoTipoMidia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DtcAtualizacao")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("dtc_atualizacao");

                    b.Property<DateTime?>("DtcDevolucao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtc_devolucao");

                    b.Property<DateTime?>("DtcEntrega")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("dtc_entrega");

                    b.Property<DateTime?>("DtcLocacao")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("dtc_locacao");

                    b.Property<int>("IdCatalogoTipoMidia")
                        .HasColumnType("int")
                        .HasColumnName("id_catalogo_tipo_midia");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("QtdTitulo")
                        .HasColumnType("int")
                        .HasColumnName("qtd_titulo");

                    b.HasKey("Id");

                    b.HasIndex("IdCatalogoTipoMidia");

                    b.HasIndex("IdCliente");

                    b.ToTable("cliente_catalogo_tipo_midia");
                });

            modelBuilder.Entity("VideoTeca.Modelos.Modelos.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("des_genero");

                    b.Property<DateTime?>("DtcAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtc_atualizacao");

                    b.HasKey("Id");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("VideoTeca.Modelos.Modelos.TipoMidia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("des_tipo_midia");

                    b.Property<DateTime?>("DtcAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtc_atualizacao");

                    b.HasKey("Id");

                    b.ToTable("tipo_midia");
                });

            modelBuilder.Entity("VideoTeca.Modelos.Modelos.CatalogoTipoMidia", b =>
                {
                    b.HasOne("VideoTeca.Modelos.Modelos.Catalogo", "Catalogo")
                        .WithMany("CatalogoTipoMidias")
                        .HasForeignKey("IdCatalogo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoTeca.Modelos.Modelos.TipoMidia", "TipoMidia")
                        .WithMany("CatalogoTipoMidias")
                        .HasForeignKey("IdTipoMidia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalogo");

                    b.Navigation("TipoMidia");
                });

            modelBuilder.Entity("VideoTeca.Modelos.Modelos.ClienteCatalogoTipoMidia", b =>
                {
                    b.HasOne("VideoTeca.Modelos.Modelos.CatalogoTipoMidia", "CatalogoTipoMidia")
                        .WithMany("ClienteCatalogoTipoMidias")
                        .HasForeignKey("IdCatalogoTipoMidia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoTeca.Modelos.Modelos.Cliente", "Cliente")
                        .WithMany("ClienteCatalogoTipoMidias")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogoTipoMidia");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("VideoTeca.Modelos.Modelos.Catalogo", b =>
                {
                    b.Navigation("CatalogoTipoMidias");
                });

            modelBuilder.Entity("VideoTeca.Modelos.Modelos.CatalogoTipoMidia", b =>
                {
                    b.Navigation("ClienteCatalogoTipoMidias");
                });

            modelBuilder.Entity("VideoTeca.Modelos.Modelos.Cliente", b =>
                {
                    b.Navigation("ClienteCatalogoTipoMidias");
                });

            modelBuilder.Entity("VideoTeca.Modelos.Modelos.TipoMidia", b =>
                {
                    b.Navigation("CatalogoTipoMidias");
                });
#pragma warning restore 612, 618
        }
    }
}
